### ISSUE TITLE
Binggung cara menggunakan?

### ISSUE THREAD

**Issue by kireniusdena** [sanicode/yii2-kilatstorage-s3#1]
Untuk setting bucket nya ?
dan endpointnya ? gymna gan?

Thx gan..

**Comment by sanicode** [comment]
```
    $aKey = 'xxx';
    $sKey = 'yyy';

    $s3 = new S3($aKey, $sKey);
    $bucket = 'cdn.eskul.net';

    $url = 'files/bla..bla..bla..jpg';

    $s3->deleteObject($bucket, $url);
```

**Comment by sanicode** [comment]
untuk menggunakannya, tidak perlu  menyebutkan endpoint, cukup sebutin bucketnya, yang terpenting aKey dan sKey nya bener, dan jangan lupa yang dimaksud URL adalah semua string setelah nama bucketnya..karena itu mengacu ke filenya langsung.

**Comment by kireniusdena** [comment]
Wah bagus, dan gk ribet.

untuk implementasi menggunakan fungsi upload :
contoh :

> $resource = yii\web\UploadedFile::getInstanceByName('gambar_saya');
> $filename = $resource->name;
> $bucket = 'mybucket';
> $url = 'mybucket.kilatstorage.com/gambar/';
> //untuk uploadnya
> $s3->putObject($bucket.$resource->saveAs(),$url );

apakah implemen bisa seperti ini gan? untuk fungsi uploadnya

**Comment by sanicode** [comment]
Untuk upload bisa pake function ini : 
`$s3->putObjectFile($files['tmp_name'], $bucket, $filename, S3::ACL_PUBLIC_READ)`

**Comment by kireniusdena** [comment]
ada error gan ketika post filenya
nemu error 
**Class 'sanicode\KilatStorageS3\STDClass' not found**
ini knpa ya?

**Comment by sanicode** [comment]
Ok, tolong buat issue baru, biar enak kita bahasnya. thanks
