### ISSUE TITLE
Class 'sanicode\KilatStorageS3\STDClass' not found, bagaimana memeperbaikinya?

### ISSUE THREAD

**Issue by kireniusdena** [sanicode/yii2-kilatstorage-s3#2]
Baru menemukan error **Class 'sanicode\KilatStorageS3\STDClass' not found**.
bagaimana memperbaikinya?

**Comment by sanicode** [comment]
Ini karena penggunaan versi PHP pada baris ke 650. Silakan dicek : 
solusi PHP 5.3
`$this->response = new stdClass();`
solusi PHP 5.4+
`$this->response = new \stdClass();`

**Comment by kireniusdena** [comment]
Ok gan udh bisa

**Comment by sanicode** [comment]
Excellence

**Comment by kireniusdena** [comment]
Ok udh bisa upload ..
dan berjalan dengan baik..
thx gan..
